trigger:
- master

jobs:
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
      pod install
      wget https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat-macos -O ../pahkat
      chmod +x ../pahkat
      git clone https://github.com/divvun/pahkat-client-core.git ../pahkat-client-core
      git clone https://github.com/divvun/divvun-ci-config.git
      cd divvun-ci-config
      sh ./install-macos.sh
    displayName: 'Install prerequisites'
    env:
      DIVVUN_KEY: $(divvunKey)
  - script: |
      set -e
      /bin/bash scripts/build-pkg.sh
    displayName: 'Build'
  - task: PublishPipelineArtifact@0
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/divvun-installer.pkg'
      artifactName: macos
    displayName: 'Publish artifact'
  - script: |
      set -e
      export PATH="$PATH:$(System.DefaultWorkingDirectory)/.."
      export DEPLOY_VERSION=`/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Pahkat/Support/Info.plist`
      sh divvun-ci-config/repo/scripts/pahkat_deploy_svn.sh https://pahkat.uit.no/repo/divvun-installer "$(System.DefaultWorkingDirectory)/divvun-installer.pkg" divvun-installer-macos $DEPLOY_VERSION
    displayName: 'Deploy to nightly channel'
    env:
      DEPLOY_SVN_USER: $(svnUser)
      DEPLOY_SVN_PASSWORD: $(svnPassword)
      DEPLOY_SVN_COMMIT: $(svnCommit)