name: Build
on: [push, repository_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: divvun-installer
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: divvun/pahkat
        ref: master
        path: pahkat
    - name: Install build tools from Pahkat for macOS
      uses: divvun/actions/pahkat/init@master
      with:
        repo: https://pahkat.uit.no/devtools/
        channel: nightly
        packages: pahkat-uploader, xcnotary
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt
    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}
    - name: Build Pahkat Daemon
      run: |
        source $RUNNER_WORKSPACE/divvun-ci-config/enc/env.sh
        cd pahkat/pahkat-rpc
        cargo build --release --features launchd --bin server
        # Copy into installer build dir
        cp ../target/release/server "$GITHUB_WORKSPACE/divvun-installer/scripts/pahkatd"
    - name: Build Divvun Installer
      run: |
        source $RUNNER_WORKSPACE/divvun-ci-config/enc/env.sh
        cd divvun-installer
        /bin/bash scripts/build.sh
    - name: Upload installer
      uses: actions/upload-artifact@v1
      with:
        name: divvun-installer
        path: divvun-installer/DivvunInstaller.pkg
    - name: Get package version from .plist
      id: version
      run: |
        export DEPLOY_VERSION=`/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$GITHUB_WORKSPACE/divvun-installer/Divvun Installer.app/Contents/Info.plist"`
        echo "::set-output name=version::$DEPLOY_VERSION"
    - name: Deploy to Pahkat
      uses: divvun/actions/deploy@master
      with:
        platform: macos
        package-id: divvun-installer
        # repo: "https://pahkat.uit.no/divvun-installer/"
        # Temporary workaround
        repo: "https://pahkat.thetc.se/divvun-installer/"
        channel: nightly
        version: ${{ steps.version.outputs.version }}
        macos-pkg-id: "no.divvun.Pahkat"
        payload-path: "${{ env.GITHUB_WORKSPACE }}divvun-installer/DivvunInstaller.pkg"
        force-deploy: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

